### ISSUE TITLE
hdf5 compression

### ISSUE THREAD

**Issue by skuschel** [sioan/auto_xtc_hdf5_converter#7]
I was playing around with compression using `h5repack` and it turns out, that a hdf5 with 200 OPAL images (about 300MB) can be compressed below 100MB by using gzip on compression level 3. This took 48sec on psanagpu114 (h5repack is single core).
Why not writing a compressed h5 in the first place?

**Comment by sioan** [comment]
that would be a silke nelson or chris o'grady question.

**Comment by sioan** [comment]
it would be in one of the repositories here
https://github.com/lcls-psana

**Comment by skuschel** [comment]
I understand, but I do not know which repository of those. Please, can you just open the issue there?

**Comment by sioan** [comment]
Just realized I repeated my self.  Sorry bout that.  Let me see if I can find the right repository.

**Comment by skuschel** [comment]
Is this fixed?

**Comment by sioan** [comment]
I met with the PCDS team earlier last week.  They do not currently have the resources to devote to this request.  I'll email you the lead's email if you wish to discuss further.

**Comment by skuschel** [comment]
Its not urgent for me. It was just a suggestion for your software. However, you should clearly leave the issue open unless its resolved or you decide to never fix it.
